// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type NewOrganization struct {
	Name        string  `json:"name"`
	Contact     string  `json:"contact"`
	Description *string `json:"description,omitempty"`
}

type Organization struct {
	ID          string `json:"id"`
	Slug        string `json:"slug"`
	Name        string `json:"name"`
	Contact     string `json:"contact"`
	Description string `json:"description"`
}
